### ISSUE TITLE
描画完了の通知が一瞬で消える

### ISSUE THREAD

**Issue by munierujp** [SugarShootingStar/visualization-twitter-grass#1]
CSVファイルのアップロード後の描画が完了時に「描画が完了しました！」という通知が表示されますが、一瞬で消えてしまいます。

`Home.vue`ファイル内で通知処理を行なっている部分：

```js
      this.$vs.notify({
        title: 'Complete!',
        text: '描画が完了しました！',
        color: 'primary',
        position: 'top-right',
        icon: 'check',
      });
```

で、`time`を適切な値に設定するとよさそうです。

cf. [Notifications - update | Vue.js Framework Components - Vuesax](https://lusaxweb.github.io/vuesax/components/notifications.html#fixed-and-function-click)

**Comment by Ancient-Scapes** [comment]
報告ありがとうございます！
デフォルトのままでも一瞬見えるし大丈夫だと思ってました……
長くしても問題はなさそうですね
該当処理、時間を指定して修正しておきます！

**Comment by Ancient-Scapes** [comment]
https://github.com/SugarShootingStar/visualization-twitter-grass/commit/fc3c922cc0e4cec8789c6894603c05f73cf31c3d

こちらのコミットで修正しました。
とりあえず `time: 5000`でやってます
