### ISSUE TITLE
ファイルアップロード後にモード切替が機能しない

### ISSUE THREAD

**Issue by munierujp** [SugarShootingStar/visualization-twitter-grass#2]
CSVファイルをアップロード前にモードを選択した場合はそのモードでカレンダーが描画されますが、アップロード後にモードを切り替えたときはカレンダーが再描画されません。
ファイルをアップロード後にモードを切り替えられないようにするか、ファイルをアップロード後にモードを切り替えたときにカレンダーを再描画するとよさそうです。

後者のほうがユーザーフレンドリーで、その場合

1. `UploadCsv.vue`ファイルで`emitObj`に全てのモードの結果を入れる
2. `Home.vue`ファイルの`data`に全てのモードの結果を保持する
3. `Home.vue`ファイルの`mode`の値によって`ResultDetail`コンポーネントと`Heatmap`コンポーネントに渡すデータを切り替える（あるいは`<template v-if>`で条件分岐させてコンポーネントごと切り替える）

のようにするといいかもしれません。
現在の挙動が意図するものだとしたらすみません。

**Comment by Ancient-Scapes** [comment]
2回目以降の描画については盲点でした…😭
たしかに全モードの処理持ってもいいかもですね！遅くなければそれで切り替えられるように書いてみます！

**Comment by Ancient-Scapes** [comment]
こちらのコミットで修正しました！
https://github.com/SugarShootingStar/visualization-twitter-grass/commit/bafb35d58fcd3e983141bf7f777e530769e4843a

**Comment by munierujp** [comment]
完璧ですね👏
